[[redirects]]
  from = "/api/*"
  to = "http://87.228.82.85:3000/api/:splat"
  status = 200
  force = true
  [[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'"